cif_dir: ${p:/public_data/CCD/components_tmp/}
file_pattern: "*.cif*"

env_path: ${p:/public_data/CCD/biomol_CCD_test.lmdb}
recipe: ${p:pipelines/recipe/ccd_recipe_book.py}

load_func: pipelines.transforms.cif_transforms.get_cif_data

n_jobs: -1
