data_dir: ${p:/home/psk6950/data/cif_raw}
file_pattern: "*.cif*"

env_path: ${p:/home/psk6950/data/BioMolDBv2_2024Oct21/cif_new2.lmdb}

recipe: ${p:pipelines/recipe/cif_recipe_book.py}
load_func: pipelines.transforms.cif_transforms.get_cif_data
transform_func: pipelines.transforms.cif_transforms.dot_transform

ccd_db_path: ${p:/home/psk6950/data/CCD/biomol_CCD.lmdb}

n_jobs: 180
chunk_size: 20000
