cif_dir: ${p:/public_data/BioMolDB_2024Oct21/cif/cif_raw}
file_pattern: "*.cif*"

env_path: ${p:/public_data/BioMolDBv2_2024Oct21/cif_new.lmdb}

recipe: ${p:pipelines/recipe/cif_recipe_book.py}
load_func: pipelines.transforms.cif_transforms.get_cif_data
transform_func: pipelines.transforms.cif_transforms.dot_transform

ccd_db_path: ${p:/public_data/CCD/biomol_CCD.lmdb}

n_jobs: 96
